final_project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['middleware' => ['auth']], function () {
    Route::resource('animes', 'AnimesController');
    Route::resource('users', 'UserController');
    Route::resource('genres', 'GenresController');
    Route::resource('profiles', 'ProfilesController')->only('index', 'store', 'update');
    Route::resource('comments', 'CommentController')->only(['store','update']);
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('excell', 'GenresExportController@export');
    Route::get('pdf', 'GenresPDFController@pdf');
    Route::get('/pdfanimes/{id}', 'AnimePDFController@pdf');
});



Auth::routes();

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

final_project/app/Genres.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Genres extends Model
{
    protected $table = "genres";
    protected $fillable = ["nama"];

    public function animes() 
    {
        return $this->hasMany('App\Animes');
    }
}

final_project/app/Http/Controllers/GenresController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use App\Genres;

class GenresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $genres = Genres::all();
        return view('genres.index', compact('genres'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('genres.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
    		'nama' => 'required|unique:genres'
    	]);
 
        Genres::create([
    		'nama' => $request->nama
    	]);
 
        Alert::success('Berhasil', 'Berhasil Membuat Genre');
    	return redirect('/genres');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $genres = Genres::find($id);
        return view('genres.edit', compact('genres'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required'
        ]);

        $genres = Genres::find($id);
        $genres->nama = $request->nama;
        $genres->update();

        Alert::success('Berhasil', 'Berhasil Diupdate');

        return redirect('/genres');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $genres = Genres::find($id);
        $genres->delete();

        Alert::success('Berhasil', 'Berhasil Dihapus');
        return redirect('/genres');
    }
}

final_project/resources/views/genres/create.blade.php
@extends('layouts.master')

@section('content')
@include('layouts.navbar')
<div class="container">
    <div class="row">
        <div class="col-lg-8 m-auto">
            <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Create New Genre</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="{{ route('genres.index') }}" method="POST">
                @csrf
                <div class="card-body">
                <div class="form-group">
                    <label for="nama">Nama Genre</label>
                    <input type="text" class="form-control" name="nama" id="nama" placeholder="Masukkan Nama Genre">
                    @error('nama')
                        <div class="alert alert-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Create</button>
                    </div>
            </form>
            </div>    
        </div>
    </div>
</div>
        
@endsection

final_project/resources/views/genres/edit.blade.php
@extends('layouts.master')

@section('content')
@include('layouts.navbar')
<div class="container">
    <div class="row">
        <div class="col-lg-8 m-auto">
            <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Edit Genre Anime {{$genres->id}}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="/genres/{{$genres->id}}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                <div class="form-group">
                    <label for="nama">Nama</label>
                    <input type="text" class="form-control" id="nama" name="nama" value="{{ old('nama', $genres->nama) }}" placeholder="Masukkan Nama genres">
                    <!-- error handling -->
                    @error('nama')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <!-- penutup error handling -->
                </div>
                </div>
            <!-- /.card-body -->
    
                <div class="card-footer">
                <button type="submit" class="btn btn-primary">Update Genre</button>
                </div>
            </form>
            </div>    
        </div>
    </div>
</div>
    
@endsection

final_project/resources/views/genres/index.blade.php
@extends('layouts.master')

@section('content')
@include('layouts.navbar')
<div class="container">
    <div class="row">
        <div class="col-lg-8 m-auto">
            <div class="card">
                <div class="card-header">
                  <h3 class="card-title">Genre Table</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <!-- Session Succes -->
                    @if(session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                    <!-- Penutup Session Succes -->
                  <a href="/genres/create" class="btn btn-primary mb-3">Create New Genre</a>
                  <a href="/excell" class="btn btn-success mb-3">Excell </a>
                  <a href="/pdf" class="btn btn-danger mb-3">PDF </a>
                  <table class="table table-bordered">
                    <thead>                  
                      <tr>
                        <th style="width: 10px">#</th>
                        <th>Nama Genre</th>
                        <th style="width: 40px">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                        <!--looping pemanggilan table pada database-->
                        @forelse ($genres as $key => $value) 
                        <tr>
                            <td> {{ $key + 1 }} </td>
                            <td> {{ $value->nama }} </td>
                            <td style="display:flex">
                                <a href="{{ route('genres.edit', ['genre' => $value->id]) }}" class="btn btn-success btn-sm">Edit</a>
                                <form action="{{ route('genres.destroy', ['genre' => $value->id]) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" value="delete" class="btn btn-danger btn-sm">
                                </form>
                            </td>
                        </tr>
                        @empty
                            <tr>
                                <td colspan="4" align="center">No Data</td>
                            </tr>                      
                        @endforelse 
                        <!--penutup looping-->
                    </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>
        </div>
    </div>
</div>
    
@endsection